### ISSUE TITLE
Task Update 1

### ISSUE THREAD

**Issue by hydroq04** [hydroq04/Photogrammetry4Agri#1]
## Tasks
This is the repository for the final project of Digital Image and Video Processing (K22 at HCMUS) about Photogrammetry and Applications in Agriculture.  
Here are the work progress (rushed) for the project:
- [ ] Exploring scientific works and finding datasets (example code, etc...) (Last date: 28/12/2024)
  - [x] Used works: DepthAnythingV2, ?
  - [ ] Used dataset: ?
- [ ] Setup the framework and model (Last date: 29/12/2024)
- [ ] Training (Last date: 01/01/2025)
- [ ] Exporting tests for report (Last date: 02/01/2025)
